### ISSUE TITLE
The Img_encoder pre-trained model incorrect!!!

### ISSUE THREAD

**Issue by jishnujayakumar** [rllab-snu/TopologicalSemanticGraphMemory#8]
Hi @bareblackfoot,

As mentioned in #6 and #7, Img_encoder link in [visualize](https://github.com/rllab-snu/TopologicalSemanticGraphMemory#visualize-the-results) not working. The **Img_encoder** in the data/graph is not loading properly—model missing keys. Please share the correct one so that [build_tgsm.ipynb](https://github.com/rllab-snu/TopologicalSemanticGraphMemory/blob/master/demo/build_tsgm_demo.ipynb) can be run.
![Img_encoder pth tar web](https://github.com/rllab-snu/TopologicalSemanticGraphMemory/assets/10737835/f422256f-4c60-4f10-b692-27077139b3f2)

**Comment by bareblackfoot** [comment]
fixed :)
Please check it!

**Comment by 07hokage** [comment]
Hi @bareblackfoot 

Based on the requirements given on the README, we tried installing and running build_tgsm.ipynb but got the following error while loading the **Img_encoder.pth**. We have tried on multiple systems still the error persists.

```
/home/experiments/TopologicalSemanticGraphMemory
/home/user/anaconda3/envs/tsgm/lib/python3.7/site-packages/habitat
Traceback (most recent call last):
  File "test_build_tsgm.py", line 59, in <module>
    img_encoder.load_state_dict(state_dict)
  File "/home/user/anaconda3/envs/tsgm/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNet:
        size mismatch for conv1.weight: copying a param with shape torch.Size([64, 3, 7, 7]) from checkpoint, the shape in current model is torch.Size([64, 4, 7, 7]).
```
